import Markdown from 'react-markdown';

export default function TechDocReport({ results }) {
    if (!results || results.length === 0) return null;

    // Build a combined tech doc from all analyzed repos
    const sections = results.map((result) => {
        const { overview, diagrams } = result;
        if (!overview) return '';

        const stats = overview.stats || {};
        const arch = overview.architecture || {};

        return `
# 📊 Technical Documentation — ${overview.repoName}

## Project Overview

| Property | Value |
|----------|-------|
| **Repository** | ${overview.repoName} |
| **Files Analyzed** | ${overview.fileCount} |
| **Languages** | ${(overview.languages || []).join(', ') || 'Unknown'} |
| **Patterns** | ${(arch.patterns || []).join(', ') || 'N/A'} |
| **Frameworks** | ${(arch.frameworks || []).join(', ') || 'N/A'} |

## Architecture Summary

${arch.summary || 'Architecture details extracted from codebase analysis.'}

## Component Statistics

| Metric | Count |
|--------|-------|
| Components | ${stats.components || 0} |
| Classes | ${stats.classes || 0} |
| DB Models | ${stats.dbModels || 0} |
| API Endpoints | ${stats.endpoints || 0} |
| External APIs | ${stats.externalApis || 0} |
| Data Flows | ${stats.flows || 0} |

## Components

The codebase is organized into **${stats.components || 0} components** with the following module dependency structure. See the **Components** tab above for the visual diagram.

## Classes & Interfaces

**${stats.classes || 0} classes** were identified. See the **Classes** tab for the UML class diagram showing inheritance and method signatures.

## Database Schema

**${stats.dbModels || 0} database models** detected. See the **Database** tab for the entity-relationship diagram.

## API Endpoints

**${stats.endpoints || 0} HTTP endpoints** discovered. See the **Endpoints** tab for the route map color-coded by HTTP method.

## External Dependencies

The application integrates with **${stats.externalApis || 0} external service(s)**. See the **External APIs** tab for the dependency graph.

## Data Flows

**${stats.flows || 0} key data flow(s)** identified, showing how requests propagate through the system. See the **Flows** tab for sequence diagrams.

---
*Generated by CodeLens v2.0*
`;
    });

    return (
        <div className="tech-doc">
            <h2>📄 Technical Documentation</h2>
            <div className="tech-doc-content">
                <Markdown>{sections.join('\n\n---\n\n')}</Markdown>
            </div>
        </div>
    );
}
